### ISSUE TITLE
ValueError: x and y must have same first dimension, but have shapes (20,) and (2,)

### ISSUE THREAD

**Issue by Coralma** [anujshah1003/own_data_cnn_implementation_keras#6]
Hi Friend,

Can you help me to check this issue?

Traceback (most recent call last):
  File "D:/projects-python/keras-sample/cnn/custom_data_cnn.py", line 217, in <module>
    plt.plot(xc,train_loss)
  File "C:\Users\ccc\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\pyplot.py", line 3317, in plot
    ret = ax.plot(*args, **kwargs)
  File "C:\Users\ccc\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\ccc\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_axes.py", line 1406, in plot
    for line in self._get_lines(*args, **kwargs):
  File "C:\Users\ccc\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 407, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "C:\Users\ccc\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 385, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "C:\Users\ccc\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\axes\_base.py", line 244, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (20,) and (2,)

**Comment by ipa-nhg-dd** [comment]
same error I have replaced with 5 but its same error

**Comment by Esaada** [comment]
Did anyone succeeded to handle this problem?

**Comment by jaggi** [comment]
Even i encountered the same error.Can anyone able to solve the error??

**Comment by tensor-flower** [comment]
Your error will disappear if you don't run the training with callbacks part. Just comment out 
```
from keras import callbacks

filename='model_train_new.csv'
csv_log=callbacks.CSVLogger(filename, separator=',', append=False)

early_stopping=callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=0, verbose=0, mode='min')

filepath="Best-weights-my_model-{epoch:03d}-{loss:.4f}-{acc:.4f}.hdf5"

checkpoint = callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')

callbacks_list = [csv_log,early_stopping,checkpoint]

hist = model.fit(X_train, y_train, batch_size=16, nb_epoch=num_epoch, verbose=1, validation_data=(X_test, y_test),callbacks=callbacks_list)
```

The reason for your error is your original training has 20 epochs, but you trained again with callbacks which only trained 2 epochs. Of course there will be error.

**Comment by mainadwitiya** [comment]
@Coralma use numpy and if x and y are values put them in an array like np.array([])

**Comment by forge1yc** [comment]
> Your error will disappear if you don't run the training with callbacks part. Just comment out
> 
> ```
> from keras import callbacks
> 
> filename='model_train_new.csv'
> csv_log=callbacks.CSVLogger(filename, separator=',', append=False)
> 
> early_stopping=callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=0, verbose=0, mode='min')
> 
> filepath="Best-weights-my_model-{epoch:03d}-{loss:.4f}-{acc:.4f}.hdf5"
> 
> checkpoint = callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
> 
> callbacks_list = [csv_log,early_stopping,checkpoint]
> 
> hist = model.fit(X_train, y_train, batch_size=16, nb_epoch=num_epoch, verbose=1, validation_data=(X_test, y_test),callbacks=callbacks_list)
> ```
> 
> The reason for your error is your original training has 20 epochs, but you trained again with callbacks which only trained 2 epochs. Of course there will be error.

Thanks for your answer!- -

**Comment by forge1yc** [comment]
@tensor-flower Thanks for your answer!- -

**Comment by Haninu** [comment]
> Your error will disappear if you don't run the training with callbacks part. Just comment out
> 
> ```
> from keras import callbacks
> 
> filename='model_train_new.csv'
> csv_log=callbacks.CSVLogger(filename, separator=',', append=False)
> 
> early_stopping=callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=0, verbose=0, mode='min')
> 
> filepath="Best-weights-my_model-{epoch:03d}-{loss:.4f}-{acc:.4f}.hdf5"
> 
> checkpoint = callbacks.ModelCheckpoint(filepath, monitor='val_loss', verbose=1, save_best_only=True, mode='min')
> 
> callbacks_list = [csv_log,early_stopping,checkpoint]
> 
> hist = model.fit(X_train, y_train, batch_size=16, nb_epoch=num_epoch, verbose=1, validation_data=(X_test, y_test),callbacks=callbacks_list)
> ```
> 
> The reason for your error is your original training has 20 epochs, but you trained again with callbacks which only trained 2 epochs. Of course there will be error.

please i have a same error but i can't find the callbacks part ! where can i find the callbacks part ??

my error is :  
raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (10,) and (11,)

**Comment by seuwins** [comment]
I meet same error message，the reason is i transform two table to arrays，but i ignore that table1 has 51 rows，table2 has 50 rows. But I use same x_value for table1/2, so there is an error.
It work well after i transform table1 to 50 rows.

**Comment by czenon1** [comment]
Hi, i have the same issue, but i dont understand how to properly use callbacks.
